# Generated by Django 4.2.7 on 2023-11-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_farmer_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=100)),
                ('F_contact', models.IntegerField(blank=True, null=True)),
                ('F_ID', models.CharField(max_length=30)),
                ('F_email', models.EmailField(max_length=100)),
                ('F_tea', models.IntegerField()),
                ('amouont', models.DecimalField(decimal_places=2, max_digits=10)),
                ('F_paid', models.BooleanField(blank=True, default=1, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
