# Generated by Django 4.2.7 on 2023-11-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_farmer_delete_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='F_paid',
            new_name='paid',
        ),
    ]
