# Generated by Django 4.2.7 on 2023-11-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_teacollection_delete_farmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacollection',
            old_name='F_contact',
            new_name='Farmer_contact',
        ),
        migrations.RenameField(
            model_name='teacollection',
            old_name='F_email',
            new_name='Farmer_email',
        ),
        migrations.RenameField(
            model_name='teacollection',
            old_name='F_id',
            new_name='Farmer_id',
        ),
        migrations.RenameField(
            model_name='teacollection',
            old_name='F_name',
            new_name='Farmer_name',
        ),
        migrations.RenameField(
            model_name='teacollection',
            old_name='F_tea',
            new_name='quantity',
        ),
    ]
