# Generated by Django 4.2.7 on 2023-11-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_amount_teacollection_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacollection',
            name='Quantity',
            field=models.CharField(max_length=50),
        ),
    ]
