# Generated by Django 4.2.7 on 2023-11-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_teacollection_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacollection',
            old_name='Quantity',
            new_name='Farmer_quantity',
        ),
    ]
