# Generated by Django 4.2.7 on 2023-11-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_teacollection_tea'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tea',
            options={'verbose_name_plural': 'Tea Collection'},
        ),
    ]
